---
Name: app
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Email:
  admin_email: noreply@ilateral.co.uk
SSViewer:
  theme: 'kube'
